### ISSUE TITLE
Scorecard: add infrastructure as code

### ISSUE THREAD

**Issue by desmarchris** [RasaHQ/financial-demo#103]
make a sample that creates a vm in GCP and deploys the financial-demo assistant, using microk8s

**Comment by ArjaanBuijk** [comment]
@desmarchris ,

My plan is to do the following:

- Implement a `blue/green` CD pipeline for AWS:
  - Triggered when something is pushed to a dedicated branch, like `aws`, or maybe more targeted branches for the different deployment methods, like `aws-docker-compose`, `aws-microk8s` & `aws-eks` .
  - The CD pipeline comes after the existing CI pipeline, and includes these steps:
    - `deploy-infrastructure` , using `CloudFormation`
    - `configure-infrastructure`, using `ansible`
    - `smoketest-green`
    - `switch-green-to-blue`
    - `smoketest-blue`
    - `cleanup-old-blue`   
- Implement/Port the CD pipeline to GCP.

Initially, I am not going to worry about the databases. Just create a new one each time.
In the end, we do need to externalize these databases, and implement the db backup & db migration steps.

**Comment by ArjaanBuijk** [comment]
#111 implemented a new CI/CD pipeline with infrastructure-as-code
