### ISSUE TITLE
CI/CD - cleanup AWS Elastic Block Store volumes

### ISSUE THREAD

**Issue by ArjaanBuijk** [RasaHQ/financial-demo#154]
When deploying Rasa enterprise to a cluster, 3 [Persistent Volumes](https://kubernetes.io/docs/concepts/storage/persistent-volumes/) are dynamically provisioned, using the `gp2` [Storage Class](https://kubernetes.io/docs/concepts/storage/storage-classes/) created during cluster creation with `eksctl`:
1. postgresql
2. redis
3. rabbit

These are [awsElasticBlockStore volumes](https://kubernetes.io/docs/concepts/storage/volumes/#awselasticblockstore).

These EBS volumes persist when:
- Uninstalling Rasa enterprise
- Deleting the EKS cluster

They must be removed separately, by the cleanup workflows.

**Comment by arjaan-shippo** [comment]
Done!

**Comment by ArjaanBuijk** [comment]
Done!
