### ISSUE TITLE
handoff is not working

### ISSUE THREAD

**Issue by AhmedNageh08** [RasaHQ/financial-demo#62]
I trained rasa in helpdesk-assistant and in financial demo and they working perfectly on chatroom_handoff.html but financial demo can't send me to helpdesk-assistant when i request handoff . just taking the handoff action request and keep chatting with financial demo 

![1](https://user-images.githubusercontent.com/26249524/89182495-1b6a8d80-d596-11ea-9051-a370771fc1c9.PNG)
![2](https://user-images.githubusercontent.com/26249524/89182500-1c032400-d596-11ea-83c4-53be8069a225.PNG)

There's no errors on any ports i run 
The ports of helpdesk_assistant:
![helpdesk port 5005](https://user-images.githubusercontent.com/26249524/89183573-badc5000-d597-11ea-895f-2b1ea2c0f56b.PNG)
![helpdesk port 5055](https://user-images.githubusercontent.com/26249524/89183577-bc0d7d00-d597-11ea-9fe9-ad874bda59e2.PNG)

The ports of financial demo:
![financial demo](https://user-images.githubusercontent.com/26249524/89183622-ccbdf300-d597-11ea-8a0e-19b5bcf93d0e.PNG)
![Uploading Inkedfinancial demo1_LI.jpg…]()

Thanks in advance

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @JustinaPetr will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by melindaloubser1** [comment]
Hi @AhmedNageh08 ! This is most likely if you were working from the master branch of RasaHQ/chatroom; the handoff branch was only merged yesterday.  If you pull master again, does it work?

**Comment by melindaloubser1** [comment]
Closing this as the issue should be fixed on the RasaHQ chatroom repo
