### ISSUE TITLE
rasa action server listen port is 5055 by default 

### ISSUE THREAD

**Issue by dingweiqings** [RasaHQ/financial-demo#75]
Rasa Version:  Rasa 1.10.8
I followed by stepd in Readme.  After I exec rasa run actions ,I see output in console ,which is 
Action endpoint is up and running on **http://localhost:5055**
Then I specify action server port using 5056 ,by execingf rasa run actions -p 5056 ,so I am glad to see finanical-demo run successfully.
My suggestion is there can specify action server port  in readme file ,thus this can be easy for newer running demo.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @rgstephens will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by rgstephens** [comment]
The use of port 5056 is documented in step #6 of the readme.
