### ISSUE TITLE
handoff not working 

### ISSUE THREAD

**Issue by rasaworkshop** [RasaHQ/financial-demo#78]
Same issue as #62

**Comment by rasaworkshop** [comment]
I have use aws hosted Chartroom.js and css

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @degiz will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by melindaloubser1** [comment]
I'm closing this since #62 already addresses it; in the future please comment on the existing issue instead of opening a new one.
