### ISSUE TITLE
Branch 2.0 is using sdk 1.0

### ISSUE THREAD

**Issue by staticdev** [RasaHQ/financial-demo#85]
This example is not really working on Rasa 2.0, right?

**Comment by sara-tagger** [comment]
Thanks for the issue, @TyDunn will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by staticdev** [comment]
@ArjaanBuijk I was able to run it with the pinned versions in PR #86.
